//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strategy
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTRUMENT
    {
        public int InstrumentId { get; set; }
        public string InstrumentName { get; set; }
        public string Symbol { get; set; }
        public string Broker { get; set; }
        public string Provider { get; set; }
        public string Market { get; set; }
        public string Exchange { get; set; }
        public string Type { get; set; }
        public string Currency { get; set; }
        public string Board { get; set; }
        public string Room { get; set; }
        public string ExpiryDate { get; set; }
        public Nullable<double> Strike { get; set; }
        public string Underlying { get; set; }
        public string CallPut { get; set; }
        public string TickTable { get; set; }
        public Nullable<double> LotSize { get; set; }
        public Nullable<double> Commission { get; set; }
        public string CreditCheckType { get; set; }
        public Nullable<int> Multiplier { get; set; }
        public Nullable<double> DiscountRate { get; set; }
    }
}
